project:
  type: website

website:
  title: "Documentation of ImmunoFusion"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: united
    css: styles.css
    toc: true

execute:
  freeze: auto


