project:
  type: website

website:
  title: "ImmunoFusion"
  navbar:
    left:
      - href: index.qmd
        text: Tutorial
      - href: methods.qmd
        text: Supplementary Methods
      - href: about.qmd
        text: About

format:
  html:
    theme: united
    css: styles.css
    toc: true

execute:
  freeze: auto


