---
title: "About"
toc: true
toc-depth: 3
toc-expand: 2

format:
  html:
    code-fold: true
    code-overflow: wrap
    code-tools: false
    code-link: true
---

## Data Availability

All the processed data can be accessed on the ImmunoFusion website. We collected ICB-related cancer data sets with tumor gene expression profiles from the dbGaP, EGA, EMBL-EBI and GSA databases. Following the accession instruction described in published ICB studies (table on the "Repository" page), we downloaded ICB patients' RNA-Seq raw sequencing data, clinical information, and response outcome information from ICB studies (if available). Curated circRNA identification results are available at Zenodo (<https://zenodo.org/doi/10.5281/zenodo.7969298>). For requesting circRNA expression matrix or other types of data, please contact the leader, Jian-Guo Zhou.

## Citation

The database is currently under submission for publication.

## Contact

If you find any bug or have any feature to request, please report it by email
  (Yankun Zhao <mailto:23happytea@gmail.com>, Shixiang Wang <mailto:shixiang1994wang@gmail.com>, Jianguo Zhou <mailto:jianguo.zhou@zmu.edu.cn>).

## Team

OncoHarmony Network is a dynamic collaborative platform dedicated to advancing the frontier of cancer immunotherapy. Bringing together diverse teams from leading universities and research institutions, our network is committed to the exploration, mining, and integration of multi-omics data in the realm of cancer research. With a focus on fostering synergy among experts in the field, OncoHarmony Network aims to construct a comprehensive resource hub and cutting-edge tools for unraveling the complexities of tumor-immune interactions. Through collective knowledge and interdisciplinary collaboration, we strive to accelerate breakthroughs in the understanding and development of effective cancer therapies.

Currently led by Dr. Shixiang Wang and Dr. Jian-Guo Zhou.

More please visit [our website](https://zhoulab.ac.cn/).